import type { Metadata } from "next";
import "./globals.css";
import { aeonik, inter } from "@/utils/constants/fonts";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`antialiased overflow-x-hidden text-foreground bg-background min-h-screen !font-default ${aeonik.variable} ${inter.variable}`}
			>
				<main>{children}</main>
			</body>
		</html>
	);
}
